###############################################################################
#                   TSMC Standard Cell Placement Constraints
#                          KITS VERSION V0.9_161208
#              Constraints Generated Date: Wed Jan  4 16:22:13 2017
###############################################################################

######################################################################
# TSMC Standard Cell Abutment Placement Constraints for ICC2
######################################################################
# Version 3.4
# Last Modified Date: 2016/08/15
######################################################################

if {![info exist RULE_NW_LEFT]} {set RULE_NW_LEFT ""}
if {$RULE_NW_LEFT != ""} {
    set_placement_spacing_label -name "CELL_NW_LEFT" -side left -lib_cells [get_lib_cells "$RULE_NW_LEFT"]
}

if {![info exist RULE_NW_RIGHT]} {set RULE_NW_RIGHT ""}
if {$RULE_NW_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_NW_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_NW_RIGHT"]
}

if {$RULE_NW_LEFT != "" && $RULE_NW_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_LEFT CELL_NW_RIGHT} { 0 2 }
}
if {$RULE_NW_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_LEFT CELL_NW_LEFT} { 0 2 }
}
if {$RULE_NW_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_RIGHT CELL_NW_RIGHT} { 0 2 }
}

if {![info exist RULE_NW2_LEFT]} {set RULE_NW2_LEFT ""}
if {$RULE_NW2_LEFT != ""} {
    set_placement_spacing_label -name "CELL_NW2_LEFT" -side left -lib_cells [get_lib_cells "$RULE_NW2_LEFT"]
}

if {![info exist RULE_NW2_RIGHT]} {set RULE_NW2_RIGHT ""}
if {$RULE_NW2_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_NW2_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_NW2_RIGHT"]
}

if {$RULE_NW2_LEFT != "" && $RULE_NW2_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW2_LEFT CELL_NW2_RIGHT} { 0 4 }
}
if {$RULE_NW2_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NW2_LEFT CELL_NW2_LEFT} { 0 4 }
}
if {$RULE_NW2_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW2_RIGHT CELL_NW2_RIGHT} { 0 4 }
}

if {![info exist RULE_NW_AREA_LEFT]} {set RULE_NW_AREA_LEFT ""}
set RULE_NW_AREA_LEFT [lsort -unique [concat $RULE_NW_AREA_LEFT "\
*/BOUNDARYPCORNERBWP* \
*/BOUNDARYRIGHTBWP* \
" ] ]
if {$RULE_NW_AREA_LEFT != ""} {
    set_placement_spacing_label -name "CELL_NW_AREA_LEFT" -side left -lib_cells [get_lib_cells "$RULE_NW_AREA_LEFT"]
}

if {![info exist RULE_NW_AREA_RIGHT]} {set RULE_NW_AREA_RIGHT ""}
set RULE_NW_AREA_RIGHT [lsort -unique [concat $RULE_NW_AREA_RIGHT "\
*/BOUNDARYLEFTBWP* \
*/BOUNDARYNINCORNERBWP* \
" ] ]
if {$RULE_NW_AREA_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_NW_AREA_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_NW_AREA_RIGHT"]
}

if {$RULE_NW_AREA_LEFT != "" && $RULE_NW_AREA_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_LEFT CELL_NW_AREA_RIGHT} { 0 5 }
}
if {$RULE_NW_AREA_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_LEFT CELL_NW_AREA_LEFT} { 0 5 }
}
if {$RULE_NW_AREA_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_RIGHT CELL_NW_AREA_RIGHT} { 0 5 }
}

if {![info exist RULE_NW_AREA2_LEFT]} {set RULE_NW_AREA2_LEFT ""}
if {$RULE_NW_AREA2_LEFT != ""} {
    set_placement_spacing_label -name "CELL_NW_AREA2_LEFT" -side left -lib_cells [get_lib_cells "$RULE_NW_AREA2_LEFT"]
}

if {![info exist RULE_NW_AREA2_RIGHT]} {set RULE_NW_AREA2_RIGHT ""}
if {$RULE_NW_AREA2_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_NW_AREA2_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_NW_AREA2_RIGHT"]
}

if {$RULE_NW_AREA_LEFT != "" && $RULE_NW_AREA2_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_LEFT CELL_NW_AREA2_LEFT} { 0 0 }
}
if {$RULE_NW_AREA_LEFT != "" && $RULE_NW_AREA2_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_LEFT CELL_NW_AREA2_RIGHT} { 0 0 }
}
if {$RULE_NW_AREA_RIGHT != "" && $RULE_NW_AREA2_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_RIGHT CELL_NW_AREA2_LEFT} { 0 0 }
}
if {$RULE_NW_AREA_RIGHT != "" && $RULE_NW_AREA2_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NW_AREA_RIGHT CELL_NW_AREA2_RIGHT} { 0 0 }
}

if {![info exist RULE_NP_LEFT]} {set RULE_NP_LEFT ""}
set RULE_NP_LEFT [lsort -unique [concat $RULE_NP_LEFT "\
*/TAPCELLBWP* \
*/TAPCELLFIN8BWP* \
*/TAPCELLFIN8FILL3BWP* \
*/TAPCELLFIN8FILL3VPPVSSBWP* \
*/TAPCELLFIN8L2R1BWP* \
*/TAPCELLFIN8VPPVBBBWP* \
*/TAPCELLFIN8VPPVBBL2R1BWP* \
*/TAPCELLFIN8VPPVSSBWP* \
*/TAPCELLFIN8VPPVSSL2R1BWP* \
*/TAPCELLL2R1BWP* \
*/TAPCELLVPPVBBBWP* \
*/TAPCELLVPPVBBL2R1BWP* \
*/TAPCELLVPPVSSBWP* \
*/TAPCELLVPPVSSL2R1BWP* \
" ] ]
if {$RULE_NP_LEFT != ""} {
    set_placement_spacing_label -name "CELL_NP_LEFT" -side left -lib_cells [get_lib_cells "$RULE_NP_LEFT"]
}

if {![info exist RULE_NP_RIGHT]} {set RULE_NP_RIGHT ""}
set RULE_NP_RIGHT [lsort -unique [concat $RULE_NP_RIGHT "\
*/TAPCELLBWP* \
*/TAPCELLFIN8BWP* \
*/TAPCELLFIN8FILL3BWP* \
*/TAPCELLFIN8FILL3VPPVSSBWP* \
*/TAPCELLFIN8L1R2BWP* \
*/TAPCELLFIN8VPPVBBBWP* \
*/TAPCELLFIN8VPPVBBL1R2BWP* \
*/TAPCELLFIN8VPPVSSBWP* \
*/TAPCELLFIN8VPPVSSL1R2BWP* \
*/TAPCELLL1R2BWP* \
*/TAPCELLVPPVBBBWP* \
*/TAPCELLVPPVBBL1R2BWP* \
*/TAPCELLVPPVSSBWP* \
*/TAPCELLVPPVSSL1R2BWP* \
" ] ]
if {$RULE_NP_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_NP_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_NP_RIGHT"]
}

if {$RULE_NP_LEFT != "" && $RULE_NP_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NP_LEFT CELL_NP_RIGHT} { 0 2 }
}
if {$RULE_NP_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_NP_LEFT CELL_NP_LEFT} { 0 2 }
}
if {$RULE_NP_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_NP_RIGHT CELL_NP_RIGHT} { 0 2 }
}

if {![info exist RULE_NP_TOP]} {set RULE_NP_TOP ""}
set RULE_NP_TOP [lsort -unique [concat $RULE_NP_TOP "\
*/TAPCELLBWP* \
*/TAPCELLFIN8BWP* \
*/TAPCELLFIN8FILL3BWP* \
*/TAPCELLFIN8FILL3VPPVSSBWP* \
*/TAPCELLFIN8L1R1BWP* \
*/TAPCELLFIN8L1R2BWP* \
*/TAPCELLFIN8L2R1BWP* \
*/TAPCELLFIN8VPPVBBBWP* \
*/TAPCELLFIN8VPPVBBL1R1BWP* \
*/TAPCELLFIN8VPPVBBL1R2BWP* \
*/TAPCELLFIN8VPPVBBL2R1BWP* \
*/TAPCELLFIN8VPPVSSBWP* \
*/TAPCELLFIN8VPPVSSL1R1BWP* \
*/TAPCELLFIN8VPPVSSL1R2BWP* \
*/TAPCELLFIN8VPPVSSL2R1BWP* \
*/TAPCELLL1R1BWP* \
*/TAPCELLL1R2BWP* \
*/TAPCELLL2R1BWP* \
*/TAPCELLVPPVBBBWP* \
*/TAPCELLVPPVBBL1R1BWP* \
*/TAPCELLVPPVBBL1R2BWP* \
*/TAPCELLVPPVBBL2R1BWP* \
*/TAPCELLVPPVSSBWP* \
*/TAPCELLVPPVSSL1R1BWP* \
*/TAPCELLVPPVSSL1R2BWP* \
*/TAPCELLVPPVSSL2R1BWP* \
" ] ]
if {$RULE_NP_TOP != ""} {
    set_placement_spacing_label -name "CELL_NP_TOP" -side left -lib_cells [get_lib_cells "$RULE_NP_TOP"]
}

if {![info exist RULE_NP_BOTTOM]} {set RULE_NP_BOTTOM ""}
set RULE_NP_BOTTOM [lsort -unique [concat $RULE_NP_BOTTOM "\
*/TAPCELLBWP* \
*/TAPCELLFIN8BWP* \
*/TAPCELLFIN8FILL3BWP* \
*/TAPCELLFIN8FILL3VPPVSSBWP* \
*/TAPCELLFIN8L1R1BWP* \
*/TAPCELLFIN8L1R2BWP* \
*/TAPCELLFIN8L2R1BWP* \
*/TAPCELLFIN8VPPVBBBWP* \
*/TAPCELLFIN8VPPVBBL1R1BWP* \
*/TAPCELLFIN8VPPVBBL1R2BWP* \
*/TAPCELLFIN8VPPVBBL2R1BWP* \
*/TAPCELLFIN8VPPVSSBWP* \
*/TAPCELLFIN8VPPVSSL1R1BWP* \
*/TAPCELLFIN8VPPVSSL1R2BWP* \
*/TAPCELLFIN8VPPVSSL2R1BWP* \
*/TAPCELLL1R1BWP* \
*/TAPCELLL1R2BWP* \
*/TAPCELLL2R1BWP* \
*/TAPCELLVPPVBBBWP* \
*/TAPCELLVPPVBBL1R1BWP* \
*/TAPCELLVPPVBBL1R2BWP* \
*/TAPCELLVPPVBBL2R1BWP* \
*/TAPCELLVPPVSSBWP* \
*/TAPCELLVPPVSSL1R1BWP* \
*/TAPCELLVPPVSSL1R2BWP* \
*/TAPCELLVPPVSSL2R1BWP* \
" ] ]
if {$RULE_NP_BOTTOM != ""} {
    set_placement_spacing_label -name "CELL_NP_BOTTOM" -side right -lib_cells [get_lib_cells "$RULE_NP_BOTTOM"]
}

if {$RULE_NP_TOP != "" && $RULE_NP_BOTTOM != ""} {
    set_placement_spacing_rule -labels {CELL_NP_TOP CELL_NP_BOTTOM} { 0 0 } -adjacent_rows
}
if {$RULE_NP_TOP != ""} {
    set_placement_spacing_rule -labels {CELL_NP_TOP CELL_NP_TOP} { 0 0 } -adjacent_rows
}
if {$RULE_NP_BOTTOM != ""} {
    set_placement_spacing_rule -labels {CELL_NP_BOTTOM CELL_NP_BOTTOM} { 0 0 } -adjacent_rows
}

if {![info exist RULE_ODMAX_1D5OD_LEFT]} {set RULE_ODMAX_1D5OD_LEFT ""}
set RULE_ODMAX_1D5OD_LEFT [lsort -unique [concat $RULE_ODMAX_1D5OD_LEFT "\
*/AN4D3BWP* \
*/AOI211OPTPAD4BWP* \
*/AOI211SKFD2BWP* \
*/AOI211SKRD2BWP* \
*/AOI21OPTPAD2BWP* \
*/AOI21OPTPAD4BWP* \
*/AOI21SKFD2BWP* \
*/AOI21SKFD3BWP* \
*/AOI21SKFD4BWP* \
*/AOI21SKFD6BWP* \
*/AOI21SKFD8BWP* \
*/AOI21SKRD3BWP* \
*/AOI22OPTPAD1BWP* \
*/AOI22OPTPAD2BWP* \
*/AOI22OPTPAD4BWP* \
*/AOI31SKRD2BWP* \
*/BENCD1BWP* \
*/BMLD2BWP* \
*/BMLD4BWP* \
*/BUFFD16BWP* \
*/BUFFD20BWP* \
*/BUFFSKFD16BWP* \
*/BUFFSKFD18BWP* \
*/BUFFSKFD20BWP* \
*/BUFFSKFD24BWP* \
*/BUFFSKFD28BWP* \
*/BUFFSKFD32BWP* \
*/BUFFSKFD36BWP* \
*/BUFFSKRD16BWP* \
*/BUFFSKRD18BWP* \
*/BUFFSKRD20BWP* \
*/BUFFSKRD24BWP* \
*/BUFFSKRD28BWP* \
*/BUFFSKRD32BWP* \
*/BUFFSKRD36BWP* \
*/BUFTD20BWP* \
*/BUFTD24BWP* \
*/BUFTD4BWP* \
*/CKBD16BWP* \
*/CKBD24BWP* \
*/CKLHQD10BWP* \
*/CKLHQD12BWP* \
*/CKLHQD14BWP* \
*/CKLHQD16BWP* \
*/CKLHQD18BWP* \
*/CKLHQD20BWP* \
*/CKLHQD24BWP* \
*/CKLHQD2BWP* \
*/CKLHQD3BWP* \
*/CKLHQD4BWP* \
*/CKLHQD6BWP* \
*/CKLHQD8BWP* \
*/CKLNQD10BWP* \
*/CKLNQD16BWP* \
*/CKLNQD18BWP* \
*/CKLNQD1BWP* \
*/CKLNQD20BWP* \
*/CKLNQD24BWP* \
*/CKLNQD4BWP* \
*/CKLNQD6BWP* \
*/CKLNQD8BWP* \
*/CKLNQOPTBBD10BWP* \
*/CKLNQOPTBBD12BWP* \
*/CKLNQOPTBBD14BWP* \
*/CKLNQOPTBBD16BWP* \
*/CKLNQOPTBBD18BWP* \
*/CKLNQOPTBBD20BWP* \
*/CKLNQOPTBBD24BWP* \
*/CKLNQOPTBBD8BWP* \
*/CKND10BWP* \
*/CKND12BWP* \
*/CKND14BWP* \
*/CKND16BWP* \
*/CKND18BWP* \
*/CKND20BWP* \
*/CKND24BWP* \
*/CKND3BWP* \
*/CKND4BWP* \
*/CKND8BWP* \
*/CKNR2D4BWP* \
*/CKNR2D8BWP* \
*/CKXOR2D2BWP* \
*/CKXOR2D4BWP* \
*/DCAP16XPBWP* \
*/DCAP16XPXNBWP* \
*/DCAP32XPBWP* \
*/DCAP32XPXNBWP* \
*/DCAP4XPBWP* \
*/DCAP64XPBWP* \
*/DCAP64XPXNBWP* \
*/DCAP8XPBWP* \
*/DCAP8XPXNBWP* \
*/DCCKBD16BWP* \
*/DCCKBD24BWP* \
*/DCCKND10BWP* \
*/DCCKND12BWP* \
*/DCCKND14BWP* \
*/DCCKND16BWP* \
*/DCCKND18BWP* \
*/DCCKND20BWP* \
*/DCCKND24BWP* \
*/DCCKND4BWP* \
*/DCCKND8BWP* \
*/DFKRPQD2BWP* \
*/DFNQD1BWP* \
*/DFNQND1BWP* \
*/DFNRPQD1BWP* \
*/DFNRPQD2BWP* \
*/DFNRPQND1BWP* \
*/DFNRPQND2BWP* \
*/DFNSNQD1BWP* \
*/DFNSNQD2BWP* \
*/DFNSNQND1BWP* \
*/DFNSRPQD1BWP* \
*/DFNSRPQD4BWP* \
*/DFQD1BWP* \
*/DFQND1BWP* \
*/DFRPQD1BWP* \
*/DFRPQD2BWP* \
*/DFRPQND1BWP* \
*/DFRPQND2BWP* \
*/DFSNQD1BWP* \
*/DFSNQD2BWP* \
*/DFSNQND1BWP* \
*/DFSNQND2BWP* \
*/DFSRPQD1BWP* \
*/EDFRPQD1BWP* \
*/EDFRPQD2BWP* \
*/FA1OPTCD4BWP* \
*/FCISD4BWP* \
*/IAO22D1BWP* \
*/IND2OPTPAD4BWP* \
*/IND2OPTPAD6BWP* \
*/IND2OPTPAD8BWP* \
*/IND3OPTPAD8BWP* \
*/INR2OPTPAD4BWP* \
*/INR2OPTPAD6BWP* \
*/INR2OPTPAD8BWP* \
*/INR3OPTPAD8BWP* \
*/INVSKFD16BWP* \
*/INVSKRD16BWP* \
*/MUX2D4BWP* \
*/MUX2D6BWP* \
*/MUX2ND8BWP* \
*/MUX3D4BWP* \
*/MUX3ND1BWP* \
*/MUX3ND2BWP* \
*/MUX3ND4BWP* \
*/MUX4D1BWP* \
*/MUX4D2BWP* \
*/MUX4D4BWP* \
*/MUX4ND1BWP* \
*/MUX4ND2BWP* \
*/MUX4ND4BWP* \
*/MUX4OPTDD1BWP* \
*/MUX4OPTDD2BWP* \
*/MUX4OPTDD4BWP* \
*/ND2OPTPAD2BWP* \
*/ND2OPTPAD4BWP* \
*/ND2OPTPAD6BWP* \
*/ND2OPTPAD8BWP* \
*/ND2SKFD10BWP* \
*/ND2SKFD12BWP* \
*/ND2SKFD16BWP* \
*/ND2SKFD20BWP* \
*/ND2SKFD2BWP* \
*/ND2SKFD3BWP* \
*/ND2SKFD8BWP* \
*/ND3OPTPAD4BWP* \
*/ND3OPTPAD6BWP* \
*/ND3OPTPAD8BWP* \
*/ND3SKFD3BWP* \
*/ND3SKFD4BWP* \
*/ND3SKFD6BWP* \
*/ND4SKFD3BWP* \
*/ND4SKFD8BWP* \
*/NR2OPTPAD2BWP* \
*/NR2OPTPAD4BWP* \
*/NR2OPTPAD6BWP* \
*/NR2OPTPAD8BWP* \
*/NR2SKRD10BWP* \
*/NR2SKRD12BWP* \
*/NR2SKRD16BWP* \
*/NR2SKRD20BWP* \
*/NR2SKRD2BWP* \
*/NR2SKRD3BWP* \
*/NR2SKRD8BWP* \
*/NR3OPTPAD4BWP* \
*/NR3OPTPAD6BWP* \
*/NR3OPTPAD8BWP* \
*/NR3SKRD3BWP* \
*/NR3SKRD4BWP* \
*/NR3SKRD6BWP* \
*/NR4SKRD3BWP* \
*/NR4SKRD8BWP* \
*/OAI211OPTPAD1BWP* \
*/OAI211OPTPAD4BWP* \
*/OAI211SKFD2BWP* \
*/OAI211SKRD2BWP* \
*/OAI21OPTPAD2BWP* \
*/OAI21OPTPAD4BWP* \
*/OAI21SKFD3BWP* \
*/OAI21SKRD2BWP* \
*/OAI21SKRD3BWP* \
*/OAI21SKRD4BWP* \
*/OAI21SKRD6BWP* \
*/OAI21SKRD8BWP* \
*/OAI22OPTPAD1BWP* \
*/OAI22OPTPAD2BWP* \
*/OAI22OPTPAD4BWP* \
*/OAI31SKFD2BWP* \
*/OR4D3BWP* \
*/SDFKSNQD1BWP* \
*/SDFKSNQD2BWP* \
*/SDFKSRPQD1BWP* \
*/SDFMQD1BWP* \
*/SDFMQD2BWP* \
*/SDFNQD1BWP* \
*/SDFNQD2BWP* \
*/SDFNQND1BWP* \
*/SDFNQND2BWP* \
*/SDFNRPQD2BWP* \
*/SDFNRPQND2BWP* \
*/SDFNSNQD2BWP* \
*/SDFNSNQND2BWP* \
*/SDFNSRPQD1BWP* \
*/SDFNSRPQD2BWP* \
*/SDFNSRPQD4BWP* \
*/SDFQD1BWP* \
*/SDFQD2BWP* \
*/SDFQND1BWP* \
*/SDFQND2BWP* \
*/SDFQOPTBBD1BWP* \
*/SDFQOPTBBD2BWP* \
*/SDFQOPTBBD4BWP* \
*/SDFQOPTBCD1BWP* \
*/SDFQOPTBCD2BWP* \
*/SDFQOPTBCD4BWP* \
*/SDFQOPTQD1BWP* \
*/SDFQOPTQD2BWP* \
*/SDFRPQD2BWP* \
*/SDFRPQND2BWP* \
*/SDFRPQOPTBBD4BWP* \
*/SDFRPQOPTBCD1BWP* \
*/SDFRPQOPTQD1BWP* \
*/SDFRPQOPTQD2BWP* \
*/SDFSNQD2BWP* \
*/SDFSNQND2BWP* \
*/SDFSNQOPTBBD1BWP* \
*/SDFSNQOPTBBD2BWP* \
*/SDFSNQOPTBBD4BWP* \
*/SDFSNQOPTBCD1BWP* \
*/SDFSRPQD1BWP* \
*/SDFSRPQD2BWP* \
*/SDFSRPQD4BWP* \
*/SDFSRPQOPTBBD1BWP* \
*/SDFSRPQOPTBBD2BWP* \
*/SDFSRPQOPTBBD4BWP* \
*/SDFSRPQOPTBCD1BWP* \
*/SDFSRPQOPTBCD4BWP* \
*/SDFSYNC1QD1BWP* \
*/SEDFQD1BWP* \
*/SEDFQD2BWP* \
*/XNR3D1BWP* \
*/XNR3D2BWP* \
*/XNR3D4BWP* \
*/XOR2D4BWP* \
*/XOR3D1BWP* \
*/XOR3D2BWP* \
*/XOR3D4BWP* \
" ] ]
if {$RULE_ODMAX_1D5OD_LEFT != ""} {
    set_placement_spacing_label -name "CELL_ODMAX_1D5OD_LEFT" -side left -lib_cells [get_lib_cells "$RULE_ODMAX_1D5OD_LEFT"]
}

if {![info exist RULE_ODMAX_1D5OD_RIGHT]} {set RULE_ODMAX_1D5OD_RIGHT ""}
set RULE_ODMAX_1D5OD_RIGHT [lsort -unique [concat $RULE_ODMAX_1D5OD_RIGHT "\
*/AOI211OPTPAD2BWP* \
*/AOI211OPTPAD8BWP* \
*/AOI211SKFD2BWP* \
*/AOI211SKRD2BWP* \
*/AOI21OPTPAD1BWP* \
*/AOI21SKFD2BWP* \
*/AOI21SKFD3BWP* \
*/AOI21SKFD4BWP* \
*/AOI21SKFD6BWP* \
*/AOI21SKRD2BWP* \
*/AOI21SKRD4BWP* \
*/AOI21SKRD6BWP* \
*/AOI22OPTPAD2BWP* \
*/AOI22OPTPAD4BWP* \
*/AOI22SKFD2BWP* \
*/AOI22SKRD2BWP* \
*/AOI31SKFD2BWP* \
*/AOI31SKRD2BWP* \
*/BENCD1BWP* \
*/BENCD2BWP* \
*/BUFFSKFD16BWP* \
*/BUFFSKFD32BWP* \
*/BUFFSKRD16BWP* \
*/BUFFSKRD32BWP* \
*/BUFTD4BWP* \
*/BUFTD6BWP* \
*/BUFTD8BWP* \
*/CKAN2D2BWP* \
*/CKBD16BWP* \
*/CKLHQD12BWP* \
*/CKLHQD14BWP* \
*/CKLHQD16BWP* \
*/CKLHQD18BWP* \
*/CKLHQD20BWP* \
*/CKLHQD24BWP* \
*/CKLHQD3BWP* \
*/CKLHQD4BWP* \
*/CKLHQD5BWP* \
*/CKLHQD6BWP* \
*/CKLHQD8BWP* \
*/CKLNQD18BWP* \
*/CKLNQD20BWP* \
*/CKLNQD24BWP* \
*/CKLNQD3BWP* \
*/CKLNQD4BWP* \
*/CKLNQD5BWP* \
*/CKLNQD6BWP* \
*/CKLNQOPTBBD16BWP* \
*/CKLNQOPTBBD18BWP* \
*/CKLNQOPTBBD24BWP* \
*/CKLNQOPTBBD4BWP* \
*/CKMUX2D4BWP* \
*/CKND10BWP* \
*/CKND12BWP* \
*/CKND14BWP* \
*/CKND16BWP* \
*/CKND18BWP* \
*/CKND1BWP* \
*/CKND20BWP* \
*/CKND24BWP* \
*/CKND8BWP* \
*/CKNR2D1BWP* \
*/CKNR2D8BWP* \
*/CKOR2D2BWP* \
*/CKXOR2D1BWP* \
*/CKXOR2D2BWP* \
*/CKXOR2D4BWP* \
*/DCAP16XPBWP* \
*/DCAP16XPXNBWP* \
*/DCAP32XPBWP* \
*/DCAP32XPXNBWP* \
*/DCAP64XPBWP* \
*/DCAP64XPXNBWP* \
*/DCAP8XPBWP* \
*/DCAP8XPXNBWP* \
*/DCCKBD10BWP* \
*/DCCKBD12BWP* \
*/DCCKBD14BWP* \
*/DCCKBD16BWP* \
*/DCCKBD18BWP* \
*/DCCKBD20BWP* \
*/DCCKBD24BWP* \
*/DCCKBD4BWP* \
*/DCCKBD5BWP* \
*/DCCKBD6BWP* \
*/DCCKBD8BWP* \
*/DCCKND10BWP* \
*/DCCKND12BWP* \
*/DCCKND14BWP* \
*/DCCKND16BWP* \
*/DCCKND18BWP* \
*/DCCKND20BWP* \
*/DCCKND24BWP* \
*/DCCKND4BWP* \
*/DCCKND5BWP* \
*/DCCKND6BWP* \
*/DCCKND8BWP* \
*/DFKRPQD1BWP* \
*/DFKRPQD2BWP* \
*/DFKRPQD4BWP* \
*/DFKSNQD1BWP* \
*/DFKSNQD2BWP* \
*/DFKSNQD4BWP* \
*/DFKSRPQD1BWP* \
*/DFKSRPQD2BWP* \
*/DFMQD1BWP* \
*/DFMQD2BWP* \
*/DFMQD4BWP* \
*/DFNQD1BWP* \
*/DFNQD2BWP* \
*/DFNQD4BWP* \
*/DFNQND1BWP* \
*/DFNQND2BWP* \
*/DFNRPQD1BWP* \
*/DFNRPQD2BWP* \
*/DFNRPQD4BWP* \
*/DFNRPQND1BWP* \
*/DFNRPQND2BWP* \
*/DFNSNQD1BWP* \
*/DFNSNQD2BWP* \
*/DFNSNQD4BWP* \
*/DFQD1BWP* \
*/DFQD2BWP* \
*/DFQD4BWP* \
*/DFQND1BWP* \
*/DFQND2BWP* \
*/DFRPQD1BWP* \
*/DFRPQD2BWP* \
*/DFRPQD4BWP* \
*/DFRPQND1BWP* \
*/DFRPQND2BWP* \
*/DFSNQD1BWP* \
*/DFSNQD2BWP* \
*/DFSNQD4BWP* \
*/DFSNQND1BWP* \
*/DFSNQND2BWP* \
*/EDFQD1BWP* \
*/EDFQD2BWP* \
*/EDFQD4BWP* \
*/EDFRPQD4BWP* \
*/FA1OPTCD1BWP* \
*/FA1OPTCD2BWP* \
*/FA1OPTSD1BWP* \
*/FA1OPTSD2BWP* \
*/FCISD1BWP* \
*/FCISND2BWP* \
*/FCSICOND4BWP* \
*/FIICOND2BWP* \
*/HA1D1BWP* \
*/HA1D2BWP* \
*/IND4D2BWP* \
*/INR3OPTPAD8BWP* \
*/INR4D1BWP* \
*/INR4D2BWP* \
*/INVSKFD16BWP* \
*/INVSKFD32BWP* \
*/INVSKRD16BWP* \
*/INVSKRD32BWP* \
*/LHCNQD1BWP* \
*/LHCNQD2BWP* \
*/LHCSNQD1BWP* \
*/LHCSNQD2BWP* \
*/LNCNQD1BWP* \
*/LNCNQD2BWP* \
*/LNCSNQD1BWP* \
*/LNCSNQD2BWP* \
*/LNCSNQD4BWP* \
*/MAOI222D1BWP* \
*/MUX2D8BWP* \
*/MUX3D4BWP* \
*/MUX3ND4BWP* \
*/MUX4ND4BWP* \
*/ND2OPTPAD16BWP* \
*/ND2OPTPAD1BWP* \
*/ND2OPTPAD2BWP* \
*/ND2OPTPAD4BWP* \
*/ND2OPTPAD8BWP* \
*/ND2SKFD10BWP* \
*/ND2SKFD12BWP* \
*/ND2SKFD16BWP* \
*/ND2SKFD20BWP* \
*/ND2SKFD24BWP* \
*/ND2SKFD3BWP* \
*/ND2SKFD4BWP* \
*/ND2SKFD6BWP* \
*/ND2SKFD8BWP* \
*/ND3OPTPAD12BWP* \
*/ND3OPTPAD1BWP* \
*/ND3OPTPAD2BWP* \
*/ND3SKFD3BWP* \
*/ND3SKFD6BWP* \
*/ND4SKFD8BWP* \
*/NR2OPTPAD16BWP* \
*/NR2OPTPAD1BWP* \
*/NR2OPTPAD2BWP* \
*/NR2OPTPAD4BWP* \
*/NR2OPTPAD8BWP* \
*/NR2SKRD10BWP* \
*/NR2SKRD12BWP* \
*/NR2SKRD16BWP* \
*/NR2SKRD20BWP* \
*/NR2SKRD24BWP* \
*/NR2SKRD3BWP* \
*/NR2SKRD4BWP* \
*/NR2SKRD6BWP* \
*/NR2SKRD8BWP* \
*/NR3OPTPAD12BWP* \
*/NR3OPTPAD1BWP* \
*/NR3OPTPAD2BWP* \
*/NR3SKRD3BWP* \
*/NR3SKRD6BWP* \
*/NR4SKRD8BWP* \
*/OAI211OPTPAD2BWP* \
*/OAI211SKFD2BWP* \
*/OAI211SKRD2BWP* \
*/OAI21OPTPAD1BWP* \
*/OAI21SKFD2BWP* \
*/OAI21SKFD4BWP* \
*/OAI21SKFD6BWP* \
*/OAI21SKRD2BWP* \
*/OAI21SKRD3BWP* \
*/OAI21SKRD4BWP* \
*/OAI21SKRD6BWP* \
*/OAI22OPTPAD2BWP* \
*/OAI22OPTPAD4BWP* \
*/OAI22SKFD2BWP* \
*/OAI22SKRD2BWP* \
*/OAI31SKFD2BWP* \
*/OAI31SKRD2BWP* \
*/OAOI211D1BWP* \
*/SDFKRPQD1BWP* \
*/SDFKRPQD2BWP* \
*/SDFKSNQD1BWP* \
*/SDFKSNQD2BWP* \
*/SDFKSRPQD1BWP* \
*/SDFKSRPQD2BWP* \
*/SDFMQD1BWP* \
*/SDFMQD2BWP* \
*/SDFNQD1BWP* \
*/SDFNQD2BWP* \
*/SDFNQD4BWP* \
*/SDFNQND1BWP* \
*/SDFNQND2BWP* \
*/SDFNRPQD1BWP* \
*/SDFNRPQD2BWP* \
*/SDFNRPQD4BWP* \
*/SDFNSNQD1BWP* \
*/SDFNSNQD2BWP* \
*/SDFNSNQD4BWP* \
*/SDFNSNQND1BWP* \
*/SDFNSNQND2BWP* \
*/SDFNSRPQD2BWP* \
*/SDFQD1BWP* \
*/SDFQD2BWP* \
*/SDFQD4BWP* \
*/SDFQND1BWP* \
*/SDFQND2BWP* \
*/SDFQOPTBBD1BWP* \
*/SDFQOPTBBD2BWP* \
*/SDFQOPTBBD4BWP* \
*/SDFQOPTBCD1BWP* \
*/SDFQOPTBCD2BWP* \
*/SDFQOPTBCD4BWP* \
*/SDFRPQD1BWP* \
*/SDFRPQD2BWP* \
*/SDFRPQD4BWP* \
*/SDFRPQND1BWP* \
*/SDFRPQND2BWP* \
*/SDFRPQOPTBBD4BWP* \
*/SDFRPQOPTBCD1BWP* \
*/SDFRPQOPTBCD2BWP* \
*/SDFRPQOPTQD1BWP* \
*/SDFRPQOPTQD2BWP* \
*/SDFSNQD1BWP* \
*/SDFSNQD2BWP* \
*/SDFSNQD4BWP* \
*/SDFSNQND1BWP* \
*/SDFSNQND2BWP* \
*/SDFSNQOPTBBD4BWP* \
*/SDFSNQOPTBCD1BWP* \
*/SDFSNQOPTBCD2BWP* \
*/SDFSNQOPTBCD4BWP* \
*/SEDFQD1BWP* \
*/SEDFQD2BWP* \
*/SEDFRPQD1BWP* \
*/SEDFRPQD2BWP* \
*/TIEHXPBWP* \
*/TIELXNBWP* \
*/XNR2D3BWP* \
*/XOR2D3BWP* \
*/XOR2D6BWP* \
*/XOR2D8BWP* \
*/XOR3D2BWP* \
*/XOR4D4BWP* \
" ] ]
if {$RULE_ODMAX_1D5OD_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_ODMAX_1D5OD_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_ODMAX_1D5OD_RIGHT"]
}

if {![info exist RULE_ODMAX_2D5OD_LEFT]} {set RULE_ODMAX_2D5OD_LEFT ""}
if {$RULE_ODMAX_2D5OD_LEFT != ""} {
    set_placement_spacing_label -name "CELL_ODMAX_2D5OD_LEFT" -side left -lib_cells [get_lib_cells "$RULE_ODMAX_2D5OD_LEFT"]
}

if {![info exist RULE_ODMAX_2D5OD_RIGHT]} {set RULE_ODMAX_2D5OD_RIGHT ""}
if {$RULE_ODMAX_2D5OD_RIGHT != ""} {
    set_placement_spacing_label -name "CELL_ODMAX_2D5OD_RIGHT" -side right -lib_cells [get_lib_cells "$RULE_ODMAX_2D5OD_RIGHT"]
}

if {$RULE_ODMAX_1D5OD_LEFT != "" && $RULE_ODMAX_2D5OD_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_1D5OD_LEFT CELL_ODMAX_2D5OD_LEFT} { 2 2 }
}
if {$RULE_ODMAX_1D5OD_LEFT != "" && $RULE_ODMAX_2D5OD_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_1D5OD_LEFT CELL_ODMAX_2D5OD_RIGHT} { 2 2 }
}
if {$RULE_ODMAX_1D5OD_RIGHT != "" && $RULE_ODMAX_2D5OD_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_1D5OD_RIGHT CELL_ODMAX_2D5OD_LEFT} { 2 2 }
}
if {$RULE_ODMAX_1D5OD_RIGHT != "" && $RULE_ODMAX_2D5OD_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_1D5OD_RIGHT CELL_ODMAX_2D5OD_RIGHT} { 2 2 }
}

if {$RULE_ODMAX_2D5OD_LEFT != "" && $RULE_ODMAX_2D5OD_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_2D5OD_LEFT CELL_ODMAX_2D5OD_RIGHT} { 1 2 }
}
if {$RULE_ODMAX_2D5OD_LEFT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_2D5OD_LEFT CELL_ODMAX_2D5OD_LEFT} { 1 2 }
}
if {$RULE_ODMAX_2D5OD_RIGHT != ""} {
    set_placement_spacing_rule -labels {CELL_ODMAX_2D5OD_RIGHT CELL_ODMAX_2D5OD_RIGHT} { 1 2 }
}

set_app_options -list {place.legalize.vertical_abutment_forbidden_pairs "1-1,1-4,1-5,2-3,2-5,3-4,4-4,4-5,5-5,1-6,4-6,5-6,7-8"}
