* moto
simple

* syntax
5 kyes: print, +, =, if, for

* rules
high cohesion, loose coupling
pcom as python fastest common functions and classes set file
using cfg files as much as possible
using proj.cfg to bootenv
class is Noun, function is verb_noun, variable is name_type

* pkg list
** common cli
linux, linux-headers, base, base-devel, pacman, pacman-contrib, sudo, ntp, gcc, gcc-fortran, gdb, strace, clisp, python, nodejs, npm, perl, tcl, git, subversion, rsync, transmission-cli, wget, axel, p7zip, unzip, unrar, xz, tree, calc, curl, openssh, nginx, postgresql, mariadb, dosfstools, blas, lapack, vim, cronie
** common gui
gvim, emacs, tk, openjdk, pulseaudio, pulseaudio-alsa, gstreamer, portmidi, flac, x264, x265, ffmpeg, mpv, smplayer, ttf-dejavu, ttf-font-awesome, chromium
** server only
*** services
nftables, vsftpd, samba, amdgpu
*** wm
xorg-server, xorg-xinit, xorg-xrandr, xorg-xprop, xautolock, xterm, i3-wm, i3status, i3lock, dmenu, dunst, ponymix
*** program
feh, mupdf, udevil
** client only
*** program
gnome, gparted, nvidia, icedtea-web, pepper-flash, filezilla, tcsh, mksh, zsh, texlive-most, texlive-langchinese, imagemagick, gimp, dia, inkscape, gv, xchm, gnuplot, graphviz, cups-pdf, bchunk, aspell-en, hunspell-en, tigervnc, freerdp, celestia, gnugo, libreoffice, android-tools, read-edid
*** multimedia
blender, cinelerra-cv, subtitleeditor, audacity, picard
** chinese and ibus
adobe-source-han-sans-cn-fonts, adobe-source-han-serif-cn-fonts
ibus, ibus-sunpinyin
** python
beautifulsoup4, diff-match-patch, Django, djangorestframework, httpie, django-reversion, ipython, jupyter, Jinja2, matplotlib, networkx, nltk, numpy, openpyxl, cython, pandas, Pillow, pip, psycopg2, mysqlclient, pytz, pyverilog, scikit-learn, scipy, setuptools, sympy, uwsgi, xlrd, xlutils, xlwt, sphinx, jieba, SQLAlchemy, texttable, nested-dict, gitpython, line_profiler, memory_profiler, pycurl, flask, paramiko, psutil, virtualenv, tox, pylint, pylint-django, nose, truepy, python-pam, pymupdf
** npm
vue, vue-router, iview, axios, js-cookie, weui
** emacs
ascii-art-to-unicode, auctex, gnugo, paredit, web-mode
** jQuery
bootstrap3, DataTables

* tools
** wiki
django wiki, trac
** bugtracker
trac
** document generator
sphinx

* emacs
** setenv
~/.emacs: (setenv "LD_LIBRARY_PATH" (concat "/usr/local/lib:/usr/lib:" (getenv "LD_LIBRARY_PATH")))
** find
find-dired: general command
find-name-dired: guide command of find-dired
find-grep: general command with grep
find-grep-dired: guide command of find-grep
** grep
grep: general command
lgrep: guide command of grep in current directory
rgrep: guide command of grep in current tree
zrgrep/rzgrep: guide command of grep in current tree including zipped files
grep-find: general command with find
** remote files (tramp)
C-x C-f <cmd> RET
/sudo::<file>
/su::<file>
/sudo:<emacs_proxy>:<file>
/su:<emacs_proxy>:<file>
/<host>:<file>
/<user>@<host>:<file>
/<user>@<host>#<port>:<file>
/<method>:<user>@<host>:<file>
/<method>:<user>@<host>#<port>:<file>
M-x shell in tramp
methods include ftp, ssh, rlogin, telnet
** batch mode
emacs --batch <file> --eval "(setq make-backup-files nil)" -f verilog-pretty-expr -f save-buffer
** rectangle
M-x rectangle-number-lines
C-u M-x rectangle-number-lines
** ansi term
prefix your standard keyboard shortcuts with C-x, M-x should be replaced with C-x M-x
** buffer coding system
revert-buffer-with-coding-system

* vim
** buffer coding system
set fileencodings=utf-8,gb18030

* python
** pre compilation
python -m compileall <file/dir>
** install modules
python setup.py install --prefix=<local_dir>
pip install --install-option="--prefix=<local_dir>" --no-index --find-links <tar_dir> <pkg_or_tar>
** tips
os.makedirs(<dir>, exist_ok=True)
shutil.rmtree(<dir>, ignore_errors=True)
pool.starmap_async(<func>, zip(<iter>), itertools.repeat(<flg>))
any(<iter>)
<dic>.get(<key>, <default_value>)
subprocess.run(<sys_cmd>, shell=True, stderr=subprocess.DEVNULL, stdout=subprocess.PIPE, check=True).stdout.decode('utf-8').strip()
** postgresql SQL
with psycopg2.connect(None, '<database>', '<user>', '<passwd>', '<host>', '<port>') as conn:
    with conn.cursor() as c:
        c.execute(<SQL>)
conn = psycopg2.connect(None, '<database>', '<user>', '<passwd>', '<host>', '<port>')
c = conn.cursor()
c.execute(<SQL>)
conn.commit()
c.close()
conn.close()
** read and overwrite file
with open(<file>, 'r+') as f:
     f_cont = f.read()
     f.seek(0)
     f.truncate()
     f.write(<new_cont>)
** reload module
import importlib
importlib.reload(<module>)
** profiling timeit
start_time = timeit.default_timer()
<statements>
end_time = timeit.default_timer()
print(end_time-start_time)
** profiling cProfile django
import cProfile, pstats
pr = cProfile.Profile()
pr.enable()
<statements>
pr.disable()
with open('prof.log', 'w') as f:
    ps = pstats.Stats(pr, stream=f).sort_stats(1)
    ps.print_stats()
** profiling cProfile python
python -m cProfile [-o output_file] myscript.py
python shell:
    import pstats
    p = pstats.Stats('output_file')
    p.strip_dirs().sort_stats(2).print_stats()
** profiling line_profiler django
def do_line_profiler(view=None, extra_view=None):
    import line_profiler
    def wrapper(view):
        def wrapped(*args, **kwargs):
            prof = line_profiler.LineProfiler()
            prof.add_function(view)
            if extra_view:
                [prof.add_function(v) for v in extra_view]
            with prof:
                resp = view(*args, **kwargs)
            prof.print_stats()
            return resp
        return wrapped
    if view:
        return wrapper(view)
    return wrapper
@do_line_profiler
def my_view(request):
    pass
** profiling line_profiler python
myscript.py:
    @profile
    def my_func():
        pass
kernprof -l myscript.py
python -m line_profiler myscript.py.lprof
** pip config
~/.config/pip/pip.conf:
[global]
index-url = https://mirrors.ustc.edu.cn/pypi/web/simple
[list]
format = columns
** license
# cert generation
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out certificate.pem -days 3565
to embed content of certificate.pem to core/op_lic.py
# mac addr
ip addr show
ifconfig
cat /sys/class/net/*/address
# license service kick off
op_license -k key.pem -c certificate.pem -f license_2018.key -I 005056ADB9A1 -e 2018/12/31
op_server -f license_2018.key
# license update
op_license -k key.pem -c certificate.pem -f license_20190630.key -I 005056ADB9A1 -e 2019/6/30
kill <PID of op_server>
op_server -f license_20190630.key

* perl
perl Makefile.PL PREFIX=<local_dir>
make
make install

* makefile
CC = g++
CFLAGS = -c -Wall -g -Os -fPIC
LDFLAGS = -l${TARGET} -L./
TARGET = cmos
TARGET_LIB = libcmos.so
OBJECTS = ${patsubst %.c, %.c.o, ${wildcard *.c}}
OBJECTS += ${patsubst %.cpp, %.cpp.o, ${shell find ./ -type f -iname "*.cpp"}}
${info $$OBJECTS is [${OBJECTS}]}
all: $(TARGET)
${TARGET}: ${TARGET_LIB}
	${CC} -o $@ $^
${TARGET_LIB}: ${OBJECTS}
        ${CC} -shared -o $@ $^
%.c.o: %.c
        ${CC} ${CFLAGS} -o $@ $^
%.cpp.o: %.cpp
        ${CC} ${CFLAGS} -o $@ $^
run: ${TARGET}
	@export LD_LIBRARY_PATH=./:${LD_LIBRARY_PATH} && ./$<
clean:
        rm ${TARGET} ${TARGET_LIB} ${OBJECTS}

* django
** settings
uwsgi_params
<proj>_nginx.conf
ln -s <proj_nginx_conf_path>/<proj>_nginx.conf /etc/nginx/conf.d/
<proj>_uwsgi.ini
<proj>/settings.py
manage.py createsuperuser
manage.py makemigrations
manage.py migrate
manage.py collectstatic
manage.py dumpdata <app> > data.json
manage.py loaddata data.json
** django-bootstrap3
'javascript_in_head': True,

* latex
** texlive package files update
mktexlsr
** latex cjk
*** encapsulated
\usepackage[encapsulated]{CJK}
\usepackage{ucs}
\usepackage[utf8x]{inputenc}
% use one of bsmi(trad Chinese), gbsn(simp Chinese), min(Japanese), mj(Korean); see:
% /usr/share/texmf-dist/tex/latex/cjk/texinput/UTF8/*.fd
\newcommand{\cntext}[1]{\begin{CJK}{UTF8}{gbsn}#1\end{CJK}}
\cntext{你好，\LaTeX}
*** directed
\documentclass[12pt, cjk]{beamer}
\usepackage[encapsulated]{CJK}
\usepackage{ucs}
\usepackage[utf8x]{inputenc}
\begin{document}
\begin{CJK}{UTF8}{gbsn}
你好，\LaTeX
\end{CJK}
\end{document}
** xecjk
\usepackage{xeCJK}
\defaultCJKfontfeatures{Scale=1.15}
\setCJKmainfont{SourceHanSerifCN-Regular}
\setCJKmonofont{SourceHanSerifCN-Regular}
\setmainfont{SourceHanSerifCN-Regular}
\renewcommand{\baselinestretch}{1.7}
\begin{document}
你好，\XeTeX
\end{document}

* git
git pull origin
git push origin master
git status
git remote show origin

sudo adduser git
sudo git init --bare /srv/ff_git.git
sudo chown -R git:git /srv/ff_git.git
which git-shell
vim /etc/passwd
git:x:1003:1003:,,,:/home/git:/usr/bin/git-shell
sudo vim ~/.ssh/authorized_keys

ssh-keygen
cat ~/.ssh/id_rsa.pub

git clone git@<server>:/srv/ff_git.git

git init
git remote add origin <url>
git fetch origin
vim .git/info/sparse-checkout
/core/
git checkout master

undoing a "git push"
git push -f origin last_known_good_commit:branch_name

undoing a "git commit"
git reset --hard

undoing a "modification"
git checkout -- .

* cleartool
cleartool ci \!:1 \!:2 `cleartool lsco -cview -me -short -r`
cleartool find . -type f -branch "brtype(<branch>)" -print
cleartool find \!:1 -version 'version(<version>) &&! lbtype(\!:2)' -print

* arch install
# dd bs=4M if=/path/to/archlinux.iso of=/dev/sdx status=progress oflag=sync

# ls /sys/firmware/efi/efivars
# ping archlinux.org
# timedatectl set-ntp true

# fdisk -l
# parted /dev/sdx
(parted) mklabel gpt
(parted) mkpart ESP fat32 1MiB 1GiB
(parted) set 1 boot on
(parted) mkpart primary ext4 1GiB 230GiB
(parted) mkpart primary linux-swap 230GiB 100%
(parted) q
# fdisk -l
# mkfs.fat -F32 /dev/sda1
# mkfs.ext4 /dev/sda2
# mkswap /dev/sda3
# swapon /dev/sda3

# mount /dev/sda2 /mnt
# mkdir /mnt/boot
# mount /dev/sda1 /mnt/boot
vi /etc/pacman.d/mirrorlist
# pacstrap /mnt base
# genfstab -U /mnt >> /mnt/etc/fstab
> fstab

# arch-chroot /mnt
# ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
# hwclock --systohc
vi /etc/locale.gen
# locale-gen
vi /etc/locale.conf
LANG=en_US.UTF-8
vi /etc/hostname
my_host_name
vi /etc/hosts
127.0.0.1	localhost
::1		localhost
127.0.1.1	my_host_name.localdomain	my_host_name

server: dhcpcd
laptop: iw, wpa_supplicant, NetworkManager(nmcli)

# mkinitcpio -p linux
# passwd

amd: > amd vi
intel: intel-ucode
efibootmgr --create --disk /dev/sda --part 1 --gpt --label "Arch Linux" --loader /vmlinuz-linux --unicode "root=/dev/sda2 rw initrd=/intel-ucode.img initrd=/initramfs-linux.img"

# exit
# umount -R /mnt
# reboot

* arch debug
systemctl --failed
systemctl reset-failed
journalctl -b 0
dmesg -l err

* amd vi
** iommu
enable iommu in uefi
set extra linux kernel parameter "iommu=pt" to make iommu work in pass through mode
** efibootmgr
efibootmgr --create --disk /dev/sda --part 1 --gpt --label "Arch Linux" --loader /vmlinuz-linux --unicode "root=/dev/sda2 rw initrd=/initramfs-linux.img iommu=pt"
efibootmgr --create --disk /dev/sda --part 1 --gpt --label "Arch Linux" --loader /vmlinuz-linux --unicode "root=/dev/sda2 rw initrd=/initramfs-linux.img iommu=pt drm.edid_firmware=edid/1920x1080.bin"
efibootmgr --create --disk /dev/sda --part 1 --gpt --label "Arch Linux" --loader /vmlinuz-linux --unicode "root=/dev/sda2 rw initrd=/initramfs-linux.img iommu=pt drm.edid_firmware=edid/ZMI0015.bin"
efibootmgr --verbose
efibootmgr -b 0000 -B
# rm /sys/firmware/efi/efivars/dump-*
# efibootmgr --bootorder XXXX,XXXX

* fstab
** check disk
lsblk -f
** server
/etc/fstab
# <file system> <dir> <type> <options> <dump> <pass>
# /dev/sda2
UUID=e4735dc5-0801-462b-9d64-58b82a435d50       /               ext4            rw,relatime,discard,data=ordered
    0 1
# /dev/sda1
UUID=6035-3B7E          /boot           vfat            rw,relatime,discard,fmask=0022,dmask=0022,codepage=437,iocha
rset=iso8859-1,shortname=mixed,utf8,errors=remount-ro       0 2
# /dev/sda3
UUID=1c592281-59d4-41ea-8873-d6934434f4f3       none            swap            defaults,discard,pri=-2 0 0
# /dev/sdb1
UUID=c83c5c95-caab-4669-a319-dbbc851a70e1       /nas/delft      ext4            rw,relatime,data=ordered        0 2
# /dev/sdc1
UUID=19a448bc-d923-459e-ac00-bab5a220c3e6       /nas/shanghai   ext4            rw,relatime,data=ordered        0 2
# /dev/sdd1
UUID=434311c3-7a36-4249-bb91-51cbf518793a       /nas/venus      ext4            rw,relatime,data=ordered,nofail,x-sy
stemd.device-timeout=1      0 2
# /dev/sde1
UUID=8dffe51b-2326-43fd-8549-1d3a319c71e5       /nas/jupiter    ext4            rw,relatime,data=ordered,nofail,x-sy
stemd.device-timeout=1      0 2
** laptop
# <file system> <dir> <type> <options> <dump> <pass>
# /dev/sda2
UUID=b78d31d2-727f-4034-8016-5c9af69d7d52	/         	ext4      	rw,relatime,discard,data=ordered	0 1
# /dev/sda1
UUID=fb432bf1-8dd9-4d6b-9a1c-4601e1996209	/boot     	ext4      	rw,relatime,discard,data=ordered	0 2
# /dev/sda3
UUID=6b835efe-6110-46c2-aea3-99d0c169e238	none      	swap      	defaults,discard  	0 0

//192.168.50.2/nas	/mnt/samba/nas		cifs	credentials=/mnt/samba/smbcredentials,x-systemd.automount	0 0

//192.168.50.2/public	/mnt/samba/public	cifs	credentials=/mnt/samba/smbcredentials,uid=cmos,gid=users,x-systemd.automount	0 0

* ssd
vi /etc/fstab
relatime,discard
cat /proc/sys/vm/swappiness
vi /etc/sysctl.d/99-sysctl.conf
vm.swappiness=1
vi /etc/udev/rules.d/60-ioschedulers.rules
cat /sys/block/sda/queue/scheduler
# set noop scheduler for non-rotating disks
ACTION=="add|change", KERNEL=="sda", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="noop"

* services
** list
dhcpcd.service
sshd.socket
nftables.service
smb.service
cronie.service
** dhcpcd
vim /etc/dhcpcd.conf
interface enp2s0f0
static ip_address=xxx.xxx.xx.2/24
static routers=xxx.xxx.xx.1
static domain_name_servers=xxx.xxx.xx.1 114.114.114.114 8.8.8.8
** sshd
vim /etc/ssh/sshd_config
AllowUsers    user1 user2
Port 39901
# systemctl edit sshd.socket
[Socket]
ListenStream=192.168.50.2:3511
FreeBind=true
** smb
smb://<ip_addr>
# useradd -g users -s /bin/bash username
# usermod --shell /usr/bin/nologin --lock username
# smbpasswd -a samba_user
# pdbedit -L -v
/etc/samba/smb.conf:
    [global]
    server min protocol = SMB2
** sftp
# useradd -g users -s /bin/bash username
** crontab
crontab -l
crontab -e
# using absolute path both in crontab -e and scripts
*/3 * * * * /usr/local/bin/python3.5 /home/firefly/ff_server/svn_monitor.py
@daily rsync -a /nas/delft/cmos/ /nas/venus/cmos/nas_temp/
@daily rsync -a /nas/delft/irabbi/ /nas/venus/irabbi/nas_temp/
@weekly rsync -a --delete /nas/venus/cmos/ /nas/jupiter/cmos/
@weekly rsync -a --delete /nas/venus/irabbi/ /nas/jupiter/irabbi/
** svn
svnadmin create /svn/<proj_dir>
/svn/<proj_dir>/conf/svnserve.conf
/svn/<proj_dir>/conf/passwd
/svn/<proj_dir>/conf/authz
svnserve -d -r /svn/<proj_dir>
port:3690
svn co svn://<ip>
svn pe svn:ignore <path>
svn resolve --accept working -R <path>
svn pg -R svn:ignore <path>
svn pg -R svn:global-ignores <path>
** prosody
admins = { "yigy@platform.sari.com" }
VirtualHost "platform.sari.com"
Component "conference.sari.com" "muc"
    restrict_room_creation = "admin"
prosodyctl cert generate platform.sari.com

* standard help
/usr/lib /lib link problems
man <prog>
<prog> -h/--help

* local installation
.a: ./configure --prefix=<local_dir>
.so: ./configure --enable-shared --prefix=<local_dir> --with-gcc=/usr/bin/gcc44
make
make test
make install

* other lib version local installation
export LD_LIBRARY_PATH
export LD_RUN_PATH
./configure LDFLAGS="-L<path1> -L<path2>" CPPFLAGS="-I<include_path>" --prefix=<local_path>

* pacman
pacman -Syu
pacman -Scc
pacman -Qm
pacman -Qdt

* aptitude
deborphan
aptitude purge <pkg>
aptitude autoclean
aptitude search '~i'

* yum
package-cleanup --quiet --leaves
/etc/yum.conf: clean_requirements_on_remove=1
yum remove <pkg>
yum list installed

* grub
/etc/default/grub: GRUB_GFXMODE=1920x1080
grub-mkconfig -o /boot/grub/grub.cfg

* nvidia
** correct DPI
/etc/X11/xorg.conf.d/20-nvidia.conf:
Section "Device"
    Identifier     "Nvidia Card"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    Option         "DPI" "96 x 96"
EndSection

* amdgpu
/etc/X11/xorg.conf.d/20-amdgpu.conf:
Section "Device"
    Identifier "AMD"
    Driver "amdgpu"
EndSection

* systemctl
systemctl list-units
systemctl enable/disable <service>
systemctl start/stop/restart <service>
systemctl --failed
systemctl reset-failed

* firewall
** iptables
-A INPUT -m state --state NEW -m tcp -p tcp -dport 5900:5999 -j ACCEPT
** nftables
Single machine
Flush the current ruleset:
# nft flush ruleset

Add a table:
# nft add table inet filter

Add the input, forward, and output base chains. The policy for input and forward will be to drop. The policy for output will be to accept.
# nft add chain inet filter input { type filter hook input priority 0 \; policy drop \; }
# nft add chain inet filter forward { type filter hook forward priority 0 \; policy drop \; }
# nft add chain inet filter output { type filter hook output priority 0 \; policy accept \; }

Add two regular chains that will be associated with tcp and udp:
# nft add chain inet filter TCP
# nft add chain inet filter UDP

Related and established traffic will be accepted:
# nft add rule inet filter input ct state related,established accept

All loopback interface traffic will be accepted:
# nft add rule inet filter input iif lo accept

Drop any invalid traffic:
# nft add rule inet filter input ct state invalid drop

New echo requests (pings) will be accepted:
# nft add rule inet filter input ip protocol icmp icmp type echo-request ct state new accept

New upd traffic will jump to the UDP chain:
# nft add rule inet filter input ip protocol udp ct state new jump UDP

New tcp traffic will jump to the TCP chain:
# nft add rule inet filter input ip protocol tcp tcp flags \& \(fin\|syn\|rst\|ack\) == syn ct state new jump TCP

Reject all traffic that was not processed by other rules:
# nft add rule inet filter input ip protocol udp reject
# nft add rule inet filter input ip protocol tcp reject with tcp reset
# nft add rule inet filter input counter reject with icmp type prot-unreachable

At this point you should decide what ports you want to open to incoming connections, which are handled by the TCP and UDP chains. For example to open connections for a web server add:
# nft add rule inet filter TCP tcp dport 80 accept

To accept HTTPS connections for a webserver on port 443:
# nft add rule inet filter TCP tcp dport 443 accept

To accept SSH traffic on port 22:
# nft add rule inet filter TCP tcp dport 22 accept

To accept incoming DNS requests:
# nft add rule inet filter TCP tcp dport 53 accept
# nft add rule inet filter UDP udp dport 53 accept

Be sure to make your changes permanent when satisifed.

# nft list ruleset > /etc/nftables.conf
# systemctl enable nftables.service

* postgreSQL
** cmds
pg_ctl init -D pg_data -o '-E UTF8 --lc-collate en_US.UTF-8 --lc-ctype en_US.UTF-8 -U admin -W'
pg_ctl start/stop/restart -D pg_data/
psql postgres -h <host> -p <port> -U <user>
create user <user> with password '<passwd>';
create database <db> owner <user>;
grant all privileges on database <db> to <user>;
\l
\d
\q
pg_dumpall -U admin -p <port> -f <db_dump>
psql -U admin -f <db_dump> postgres
** cfg
pg_data/pg_hba.conf:
    local all all md5
    host all all 0.0.0.0/0 md5
    host all all ::/0 md5
pg_data/postgresql.conf:
    listen_addresses = '*'
    post = 5432
    max_connections = 200

* MySQL
** index
db dir: /var/lib/mysql
cfg dir: /usr/share/mysql (mysql.server)
glb cfg dir: /etc/mysql
script: /etc/init.d/mysql
** cmds
mysql <db> -h <host> -P <port> -u <user> -p
insert into mysql.user(Host,User,Password) values("localhost","<user>",password("<passwd>"));
create database <db>;
grant all privileges on <db>.* to <user>@localhost identified by "<passwd>";
flush privileges;
insert into mysql.user(Host,User,Password) values("%","<user>",password("<passwd>"));
grant all privileges on <db>.* to <user>@"%" identified by "<passwd>";
flush privileges;
revoke all privileges on <db>.* from <user>@"%" identified by "<passwd>";
flush privileges;
show grants for <user>@localhost;
mysqladmin -u root -p password <new_passwd>

* uwsgi
uwsgi --ini sprd_site_uwsgi.ini --pidfile=uwsgi.pid &
uwsgi --stop uwsgi.pid
uwsgi --reload uwsgi.pid

* nginx
nginx -t
/etc/nginx/nginx.conf:
    include ./conf.d/*;
nginx
nginx -s stop
nginx -s reload

* tomcat
tomcat8 home dir: /usr/share/tomcat8
/usr/share/tomcat8/conf/tomcat-users.xml:
    <role rolename="tomcat"/>
    <role rolename="manager-script"/>
    <role rolename="manager-gui"/>
    <user password="tomcat" roles="tomcat, manager-script, manager-gui,admin" username="tomcat"/>

* irun
** pcom
-work <lib_name>
cds.lib:
    INCLUDE <cds_lib>
    DEFINE <lib_name> <lib_dir>
** analysis and elaboration options
irun -c -64bit -licqueue -status -status3 -ALLOWREDEFINITION -nowarn WARIPR -nowarn CUVWSP -nowarn CSINFI -nowarn NOCMIC -nowarn ILLORD -nowarn CUFEPC -nowarn CUDEFB -nowarn ZROMCW -nowarn MEMODR -timescale '1ns/1ps' -vlogext vh -vlogext hv -vlogext fv -nospecify -ntcnotchks -nclibdirpath <nc_lib_dir> -access +r -top <top_hier> -f <verilog_lst> -makelib <vhdl_lib> -lexpragma -ignore_extrachar -nowarn IGXCHAR -nowarn INVPRG -nowarn -V93 -f <vhdl_lst> -endlib -l <com_log>
** simulation options
irun -R -64bit -input <sim_tcl> -uselic IES:IESXL -licqueue -nclibdirpath <nc_lib_dir> -l <sim_log>
** coverage elaboration options
-covfile <cov_filter> -covoverwrite
** coverage simulation options
-covfile <cov_filter> -covtest <cov_name> -covoverwrite -covworkdir <cov_work_dir>
** imc options
imc -64bit -exec <imc_tcl>
imc -64bit -gui -init <imc_tcl>
** tcl options
logfile -overwrite <tcl_log>; run;
load -run <cov_dir>;
load -refinement <vRefine1>; load -refinement <vRefine2>;
merge_config -source <dut_hier> -target <dut_hier>
merge -overwrite -runfile <merge_lst> -out <cov_dir>;
merge -overwrite <cov_dir1> <cov_dir2> -out <merge_dir>;
report -overwrite -detail -html -out <rpt_dir> -inst <rpt_hier>... -grading covered
report -metrics toggle -uncovered -detail -text -out <rpt_txt> -inst <rpt_hier>... -grading covered
merge_lst:
    <case1_dir>/case1/cov_work/scope/*
    <case2_dir>/case2/cov_work/scope/*

* vcs
** pcom
-work <lib_name>
synopsys_sim.setup:
    WORK > DEFAULT
    DEFAULT: <lib_dir>
    <lib_name>: <lib_dir>
** analysis options
vlogan -full64 -sverilog -assert svaext -timescale=1ns/1ps -error=noMPD +warn=noUIWN +warn=noSV-LCM-PPWI +warn=noPHNE +v2k +verilog1995ext+v95 +verilog2001ext+v +verilog2001ext+vh +verilog2001ext+hv +verilog2001ext+fv +verilog2001ext+vams +nospecify +notimingcheck -f <verilog_lst> -l <vlogan_log>
vhdlan -full64 -skip_translate_body -f <vhdl_lst> -l <vhdlan_log>
vlogan -full64 -sverilog -ntb_opts uvm-1.1 +define+UVM_REG_DATA_WIDTH=32 +define+UVM_REG_ADDR_WIDTH +define+UVM_PACKER_MAX_BYTES=1500000 -l <uvm_log>
** elaboration options
vcs -full64 -sverilog -lca +vcs+lic+wait +error+999 +warn=noTFIPC +warn=noSV-SELS +warn=noSVA-LDRF +warn=noVCM-NOCOV-ENC +warn=noVCM-HFUFR +warn=noVCS-NODRCO +nospecify +lint=PCWM -top <top_hier> -debug_region=cell -debug_access+r -o <sim_obj> -l <elab_log>
** simulation options
empty_sim -assert nopostproc -l <sim_log>
** coverage elaboration options
-cm_constfile <const_lst>
-cm_hier <cov_filter>
-cm line+cond+fsm+tgl+branch
-cm_line contassign -cm_noconst -cm_seqnoconst
-cm_tgl portsonly
-cm_libs celldefine
-power=coverage+cov_pst_transition+dump_hvp
** coverage simulation options
-cm_name <cov_name>
-cm line+cond+fsm+tgl+branch
** urg options
urg -full64 -f <merge_lst> -dbname <cov_dir> -noreport
urg -full64 -dir <cov1_dir> -dir <dvo2_dir> -dbname <merge_dir> -noreport
urg -full64 -elfile <el1_file> -elfile <el2_file>
merge_lst:
    <case1_dir>/case1.vdb
    <case2_dir>/case2.vdb
** tcl options
run
** coverage gui options
verdi -cov -elfile <el1_file> -elfile <el2_file> -covdir <vdb_dir>
** caution
vhdl entity not supported in <cov_filter>

* verdi
** pcom
-lib <lib_name>
novas_rc:
    [Library]
    <lib_name> = <lib_dir>
-L <lib_name>
** analysis options
vhdlcom -93 -sup_sem_error -smartorder -f <vhdl_lst>
vericom -sv +systemverilogext+sv +v95ext+v95 +verilog2001ext+v -ignorekwd_config -f <verilog_lst>
** run options
verdi -undockWin -nologo
verdi -autoalias -sv +v2k -ssv -ssy -undockWin -nologo
** nWave options
nWave -ssf <fsdb> -sswr <novas_rc>

* xorg
** Xresources
xrdb ~/.Xresources
xrdb -merge ~/.Xresources
** xmodmap
xmodmap -pke

* bash
** files leaving
shopt -s extglob
rm !(<file1>|<dir1>|<file2>)
** login shell modification
chsh -s <shell> <user>
** find exec
find -type f -perm -a+x -exec chmod -x {} \;

* integrity check
pwck
grpck

* sed
sed -i -E "s/<regex>/<string>/g" <files>

* rsync
rsync -avh --delete </src_dir/> </tar_dir/>

* httpie
http :8000/xiaoshi/post/read_list X-AccessToken:11111 sel==all offset==0 limit==4
http -a guanyu_yi POST :8000/xcareer/runner/resumes/ <<< '[{}]'

* xfreerdp
xfreerdp -g 1920x960 --ignore-certificate -u <user> -p <passwd> --plugin rdpsnd <host>

* cinelerra
/etc/sysctl.conf: kernel.shmmax = 0x7fffffff
sysctl -p

* media format conversion
** lame
lame is used to convert mp3 vbr to cbr (Audacity for advanced conversion)
** wma2mp3
for i in *.wma;
do mplayer -vo null -vc dummy -af resample=44100 -ao pcm:waveheader "$i" && lame -m j -h --vbr-new -b 192 audiodump.wav -o "`basename "$i" .wma`.mp3";
done;
rm -f audiodump.wav
** mp32wma
pacpl -t mp3 --bitrate 320 -o wma -r <src_dir>
** 2mp4
ffmpeg -i <wmv_file> -r 60 -b:a 192k -b:v 2000k <mp4_file>
ffmpeg -i <mov_file> -r 60 -ar 44100 -b:a 192k -b:v 2000k <mp4_file>
** ape&cue2flac
ffmpeg -i <ape_file> <wav_file>
bchunk -w <wav_file> <cue_file> <new_file_prefix>
flac --best <new_file_prefix>*
** standard sample rates
192 224 256 320

* firefox
** uri_2_fileuri
~/.mozilla/firefox/defaults/profile/user.js:
    user_pref("capability.policy.policynames", "localfilelinks");
    user_pref("capability.policy.localfilelinks.sites", "<site1_url> <site2_url>");
    user_pref("capability.policy.localfilelinks.checkloaduri.enabled", "allAccess");
    user_pref("browser.backspace_action", 0);
    user_pref("browser.startup.homepage", "<home_url>")
** link real path to static path
cp /home/cmos/log_file $SITE_ROOT/media/home/cmos/log_file
<a href="/media/home/cmos/log_file">log_file_link</a>

* thunderbird
network.protocol-handler.warn-external.ftp = true
network.protocol-handler.warn-external.http = true
network.protocol-handler.warn-external.https = true
mail.biff.use_system_alert = true

* android
** nexus
sed -i 's/ro.setupwizard.network_required=true/ro.setupwizard.network_required=false/g' /system/build.prop
* openfortivpn
** connection
sudo openfortivpn 116.228.193.14:5550 -u ss -p ss@1234 --trusted-cert a6cdc5b1bef884b26c94e4851d9b6185df70f3a53e3f124ed87b8acbf7c47614
* deff
module DEFF (
  input clock, reset, in,
  output out
);

  reg trig1, trig2;

  assign out = trig1^trig2;

  always @(posedge clock, posedge reset) begin
    if (reset)  trig1 <= 0;
    else  trig1 <= in^trig2;
  end

  always @(negedge clock, posedge reset) begin
    if (reset)  trig2 <= 0;
    else  trig2 <= in^trig1;
  end
endmodule
