#! /usr/bin/env python3
"""
Author: Guanyu Yi @ OnePiece Platform Group
Email: guanyu_yi@alchip.com
Description: op platform unique entrance
"""

from core import op_top

if __name__ == "__main__":
    op_top.main()
