#cdc_cdc_abstract.tcl
set WAIVE_cdc_cdc_abstract { \
Param_clockreset07 \
Clock_setup01 \
Param_clockreset06 \
SGDC_meta_monitor_attributes01 \
LP_POWERDATA_CHECK \
LP_POWERDATA_READ \
Ar_auxi01 \
PrecompileLibCheck01 \
PrecompileLibCheck02 \
PrecompileLibCheck03 \
PrecompileLibCheck04 \
ElabSummary \
SGDC_assume_path01 \
SGDC_sdcschema02 \
SGDC_clock05 \
SGDC_clock09 \
SGDC_force_ta05 \
SGDC_require_path03 \
SGDC_require_value03 \
SGDC_voltagedomain05 \
SGDC_voltagedomain06 \
SGDC_voltagedomain07 \
SGDC_powerdomainoutputs02 \
SGDC_supply01 \
SGDC_waive01 \
SGDC_waive02 \
SGDC_waive03 \
SGDC_waive04 \
SGDC_waive05 \
SGDC_waive06 \
SGDC_waive07 \
SGDC_waive08 \
SGDC_waive09 \
SGDC_waive10 \
SGDC_waive11 \
SGDC_waive12 \
SGDC_waive13 \
SGDC_waive21 \
SGDC_waive22 \
SGDC_waive30 \
SGDC_waive32 \
SGDC_waive33 \
SGDC_waive36 \
SGDC_waive38 \
SGDC_fifo01 \
SGDC_libgroup01 \
SGDC_libgroup02 \
SGDC_libgroup04 \
SGDC_power_data01 \
SGDC_ungroup01 \
SGDC_abstract_port06 \
SGDC_abstract_port14 \
SGDC_abstract_port15 \
SGDC_abstract_port18 \
SDC2SGDC_INFO \
SDC_ParamSanityCheck \
SDC_Sanity_Rule \
sdc_init_rule \
CMD_ignorelibs01 \
ReportRuleNotRun \
SGDC_generated_clock03 \
SGDC_generated_clock04 \
SGDC_generated_clock05 \
SGDC_quasi_static_style02 \
SGDC_syncresetstyle01 \
SGDC_network_allowed_cells01 \
SGDC_numflops01 \
SGDC_numflops07 \
SGDC_numflops08 \
SGDC_numflops09 \
SGDC_clocksense04 \
SGDC_clock_relation05a \
SGDC_clock_relation05b \
SGDC_sync_cell08a \
SGDC_sync_cell09a \
SGDC_qualifier06 \
SGDC_cdc_waive03 \
SGDC_qualifier09 \
SGDC_qualifier15 \
SGDC_allow_combo_logic01 \
SGDC_reset_filter_path01 \
SGDC_cdc_false_path05 \
Param_clockreset05 \
Ac_sanity01 \
Ac_sanity06 \
Ac_license01 \
SGDC_reset_synchronizer07 \
ReportStopSummary \
ReportIgnoreSummary \
InferBlackBox \
SGDC_waive37 \
SGDC_waive24 \
SGDC_waive25 \
SGDC_waive31 \
SGDC_waive35 \
DetectTopDesignUnits \
GenerateConfMap \
Pragma_setupa \
SDC2SGDCPARSE \
SGDC_testmode03 \
Pragma_setupb \
_vhMeta01 \
_meta_delay01 \
CheckCelldefine \
checkSGDC_01 \
checkSGDC_03 \
checkSGDC_08 \
SGDC_memorywritepin04 \
SGDC_reset02 \
SGDC_reset03 \
SGDC_waive23 \
SGDC_waive26 \
SGDC_waive27 \
SGDC_waive29 \
SGDC_libgroup03 \
SGDC_ungroup02 \
_abstractPortSGDC \
SGDC_abstract_port03 \
SGDC_abstract_port04 \
SGDC_abstract_port05 \
SGDC_abstract_port07 \
SGDC_abstract_port08 \
SGDC_abstract_port10 \
SGDC_abstract_port11 \
SGDC_abstract_port12 \
SGDC_abstract_port13 \
SGDC_sdcschema01 \
_cdc_save_license01 \
_syncResetStyleRTL \
_deltaDelay \
_deltaDelay \
_deltaDelayNom \
Ac_multitop01 \
AcOvlRtl \
AcOvlRtl \
Ac_svasetup01 \
ReportUngroup \
SGDC_allow_combo_logic02 \
_portRetenClocknReset \
_portReten \
SGDC_meta_design_hier01 \
LP_POWERDATA_INFO \
SGDC_abstract_port21 \
SDC2SGDC_WRN01 \
SDC2SGDC_STX01 \
SGDC_input02 \
SGDC_input03 \
SGDC_output02 \
SGDC_output04 \
SGDC_numflops03a \
SGDC_numflops03b \
SGDC_numflops12 \
SGDC_sync_cell02b \
SGDC_sync_cell11 \
SGDC_qualifier02c \
SGDC_qualifier03c \
Ac_qualifier_depth \
LPwrRulesSetup \
Domain_Conflict01 \
Domain_Matrix01 \
Domain_Missing01 \
SDC_Mapping01 \
SDC2SGDCPARSEW \
SGDC_quasi_static_style01 \
SignalTypeSetup \
_allowInst \
_ipblock \
_rstSyncCellInst \
_syncCellDelayedQualifier \
_repeaterCellInst \
_abstract_port \
Clock_setup02 \
Clock_prop \
Reset_prop \
SGDC_generated_clock06 \
SGDC_clock_sanity01 \
Propagate_Clocks \
_syncreset_prop \
_syncc \
_syncb \
_resetPathCross \
FalsePathSetup \
_fifo01 \
_syncfifo \
_syncUDfifo \
_syncdw \
_syncd \
_syncg \
_sync_clock \
_sync_gp \
_sync_and \
_synci \
_sync_qualifier \
SGDC_fifo11 \
SGDC_fifo12 \
SGDC_fifo13 \
SGDC_fifo14 \
Gen_diff01 \
_debugData \
Ac_Sync_Init \
_propagate_cdcAttrib \
Ar_Cross_Init \
SGDC_cdc_define_transition01 \
UPF_lowpower08PR \
UPF_lowpower08 \
Setup_check01 \
Setup_check02 \
Info_Case_Analysis \
SGDC_set_case_analysis_LC \
SGDC_signal_in_domain02 \
SGDC_signal_in_domain04 \
SGDC_numflops03c \
SGDC_numflops04 \
SGDC_numflops05 \
SGDC_numflops06 \
SGDC_numflops11 \
SGDC_numflops13 \
SGDC_numflops14 \
SGDC_numflops15 \
SGDC_clocksense02 \
SGDC_clocksense03 \
SGDC_sgclkgroup01 \
SGDC_sgclkgroup02 \
SGDC_sgclkgroup03 \
SGDC_clock_relation01a \
SGDC_clock_relation01b \
SGDC_clock_relation01c \
SGDC_clock_relation02a \
SGDC_clock_relation02b \
SGDC_clock_relation02c \
SGDC_clock_relation03b \
SGDC_clock_relation04b \
SGDC_clock_relation06b \
SGDC_clock_relation06c \
CheckClockRelationSetup \
SGDC_gray_signals01 \
SGDC_gray_signals02 \
SGDC_gray_signals03 \
SGDC_qualifier02a \
SGDC_qualifier03a \
SGDC_qualifier04 \
SGDC_qualifier05 \
SGDC_qualifier08 \
QualifierSetup \
ResetSynchronizerSetup \
SGDC_validation_filter_path03 \
SGDC_qualifier10 \
SGDC_qualifier11 \
SGDC_qualifier12 \
SGDC_qualifier13 \
SGDC_qualifier14 \
SGDC_qualifier16 \
SGDC_qualifier18 \
SGDC_qualifier19a \
SGDC_qualifier19b \
SGDC_qualifier19c \
SGDC_qualifier20b \
SGDC_qualifier21 \
SGDC_qualifier22 \
SGDC_qualifier23 \
SGDC_qualifier26 \
SGDC_qualifier27 \
SGDC_qualifier28 \
SGDC_qualifier29 \
SGDC_qualifier30 \
SGDC_qualifier31 \
SGDC_virtualclock01 \
SGDC_virtualreset01 \
SGDC_abstract_port19 \
SGDC_abstract_port20 \
SGDC_abstract_port24 \
SGDC_abstract_port23 \
RFPSetup \
SGDC_quasi_static_rdc02a \
SGDC_quasi_static_rdc02b \
SGDC_quasi_static_rdc02c \
QSRDCSetup \
SGDC_reset_filter_path02a \
SGDC_reset_filter_path02b \
SGDC_reset_filter_path02c \
SGDC_reset_filter_path03a \
SGDC_reset_filter_path03b \
SGDC_reset_filter_path03c \
SGDC_reset_filter_path04b \
SGDC_reset_filter_path07a \
SGDC_reset_filter_path07b \
SGDC_reset_filter_path07c \
SGDC_define_reset_order03 \
SGDC_define_reset_order04 \
SGDC_define_reset_order05 \
SGDC_cdc_false_path06 \
SGDC_cdc_false_path07 \
SGDC_cdc_false_path08 \
SGDC_cdc_false_path09 \
CDCSet_License01 \
Propagate_Resets \
_reset_sync \
Setup_blackbox01 \
Ac_abstract01 \
_clkWrapModules \
_clock_hier_rules \
Ar_sync_init \
_constrCoverage \
SGDC_clockreset02 \
Param_clockreset02 \
Param_clockreset04 \
Setup_clockreset01 \
Clock_check07 \
Reset_check08 \
SGDC_noclockcell_start01 \
Ac_initseq01 \
Ac_init01 \
_ac_Auxi01 \
Ac_sanity02 \
_glitch_init \
Ac_initstate01 \
Ac_conv02setup01 \
Ac_abs01 \
AllowComboLogicSetup \
Ac_upfsetup02 \
Ac_upfsetup01 \
Ac_psync_init \
Ac_psetup01 \
Clock_exit01 \
SGDC_reset_synchronizer02 \
SGDC_reset_synchronizer04 \
SGDC_reset_synchronizer06 \
SGDC_reset_synchronizer08 \
SGDC_reset_synchronizer10 \
Ac_report01 \
AnalyzeBBox \
ReportCheckDataSummary \
}

#Setup_port01 \
#
#
