#constraints_sdc_redundancy.tcl
set WAIVE_constraints_sdc_redundancy { \
Const_Sanity_Rule \
ParamSanityCheck01a \
ConsReportAuxi01 \
Block10_Data \
Delay_Auxi \
Gen33_Data \
XBuf_Auxi01 \
Consis_Auxi \
PrecompileLibCheck01 \
PrecompileLibCheck02 \
PrecompileLibCheck03 \
PrecompileLibCheck04 \
ElabSummary \
SGDC_assume_path01 \
SGDC_sdcschema02 \
SGDC_clock05 \
SGDC_clock09 \
SGDC_force_ta05 \
SGDC_require_path03 \
SGDC_require_value03 \
SGDC_voltagedomain05 \
SGDC_voltagedomain06 \
SGDC_voltagedomain07 \
SGDC_powerdomainoutputs02 \
SGDC_supply01 \
SGDC_waive01 \
SGDC_waive02 \
SGDC_waive03 \
SGDC_waive04 \
SGDC_waive05 \
SGDC_waive06 \
SGDC_waive07 \
SGDC_waive08 \
SGDC_waive09 \
SGDC_waive10 \
SGDC_waive11 \
SGDC_waive12 \
SGDC_waive13 \
SGDC_waive21 \
SGDC_waive22 \
SGDC_waive30 \
SGDC_waive32 \
SGDC_waive33 \
SGDC_waive36 \
SGDC_waive38 \
SGDC_fifo01 \
SGDC_libgroup01 \
SGDC_libgroup02 \
SGDC_libgroup04 \
SGDC_power_data01 \
SGDC_ungroup01 \
SGDC_abstract_port06 \
SGDC_abstract_port14 \
SGDC_abstract_port15 \
SGDC_abstract_port18 \
SDC2SGDC_INFO \
SDC_ParamSanityCheck \
SDC_Sanity_Rule \
sdc_init_rule \
CMD_ignorelibs01 \
ReportRuleNotRun \
ReportStopSummary \
ReportIgnoreSummary \
InferBlackBox \
SGDC_waive37 \
SGDC_waive24 \
SGDC_waive25 \
SGDC_waive31 \
SGDC_waive35 \
DetectTopDesignUnits \
GenerateConfMap \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
SDC2SGDCPARSE \
SDCPARSE \
Nom_Le_Call \
Hier_Constraints_Check \
DomainSanityCheck \
SDC2SGDCPARSE \
PRDGenAuxi \
SGDC_testmode03 \
CheckCelldefine \
checkSGDC_01 \
checkSGDC_03 \
checkSGDC_08 \
SGDC_memorywritepin04 \
SGDC_reset02 \
SGDC_reset03 \
SGDC_waive23 \
SGDC_waive26 \
SGDC_waive27 \
SGDC_waive29 \
SGDC_libgroup03 \
SGDC_ungroup02 \
_abstractPortSGDC \
SGDC_abstract_port03 \
SGDC_abstract_port04 \
SGDC_abstract_port05 \
SGDC_abstract_port07 \
SGDC_abstract_port08 \
SGDC_abstract_port10 \
SGDC_abstract_port11 \
SGDC_abstract_port12 \
SGDC_abstract_port13 \
SGDC_sdcschema01 \
ReportUngroup \
InternalRule01a \
ParamSanityCheck01b \
Delay_Split \
SGDC_abstract_port21 \
SDC2SGDC_WRN01 \
SDC2SGDC_STX01 \
Clk_Gen21 \
Clk_Trans16 \
Constraints_MasterRule \
GenSDCData \
GenSDCCrossingData \
Block10 \
DomainAnalysis \
Clk_Uncert07 \
High_Fan03a \
High_Fan03b \
Inp_Del07a \
Op_Del07a \
False_Path04a \
MCP04a \
Disable_Timing02 \
SDC_Report01 \
Show_Case_Analysis \
Show_Clock_Propagation \
Domain_Conflict01 \
Domain_Matrix01 \
Domain_Missing01 \
SDC_Mapping01 \
SDC2SGDCPARSEW \
Inp_Del09 \
Op_Del09 \
False_Path03 \
MCP03 \
AnalyzeBBox \
ReportCheckDataSummary \
}

