#dft_dft_best_practice.tcl
set WAIVE_dft_dft_best_practice { \
PrecompileLibCheck01 \
PrecompileLibCheck02 \
PrecompileLibCheck03 \
PrecompileLibCheck04 \
ElabSummary \
SGDC_assume_path01 \
SGDC_sdcschema02 \
SGDC_clock05 \
SGDC_clock09 \
SGDC_force_ta05 \
SGDC_require_path03 \
SGDC_require_value03 \
SGDC_voltagedomain05 \
SGDC_voltagedomain06 \
SGDC_voltagedomain07 \
SGDC_powerdomainoutputs02 \
SGDC_supply01 \
SGDC_waive01 \
SGDC_waive02 \
SGDC_waive03 \
SGDC_waive04 \
SGDC_waive05 \
SGDC_waive06 \
SGDC_waive07 \
SGDC_waive08 \
SGDC_waive09 \
SGDC_waive10 \
SGDC_waive11 \
SGDC_waive12 \
SGDC_waive13 \
SGDC_waive21 \
SGDC_waive22 \
SGDC_waive30 \
SGDC_waive32 \
SGDC_waive33 \
SGDC_waive36 \
SGDC_waive38 \
SGDC_fifo01 \
SGDC_libgroup01 \
SGDC_libgroup02 \
SGDC_libgroup04 \
SGDC_power_data01 \
SGDC_ungroup01 \
SGDC_abstract_port06 \
SGDC_abstract_port14 \
SGDC_abstract_port15 \
SGDC_abstract_port18 \
SDC2SGDC_INFO \
SDC_ParamSanityCheck \
SDC_Sanity_Rule \
sdc_init_rule \
CMD_ignorelibs01 \
ReportRuleNotRun \
dftSetup \
dftSGDCSTX_073 \
dftSGDCSTX_058 \
dftCumulativeFaultStatusFileCheck \
dftSGDCSTX_051 \
dftSGDCSTX_053 \
dftSGDCSTX_054 \
dftSGDCSTX_055 \
dftSGDCSTX_072 \
dftSGDCSTX_074 \
dftSGDCSTX_076 \
dftSGDCSTX_077 \
dftSGDCSTX_078 \
dftSGDCSTX_075 \
dftParamCheck_01 \
ReportStopSummary \
ReportIgnoreSummary \
InferBlackBox \
SGDC_waive37 \
SGDC_waive24 \
SGDC_waive25 \
SGDC_waive31 \
SGDC_waive35 \
DetectTopDesignUnits \
GenerateConfMap \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SDC2SGDCPARSE \
SGDC_testmode03 \
CheckCelldefine \
checkSGDC_01 \
checkSGDC_03 \
checkSGDC_08 \
SGDC_memorywritepin04 \
SGDC_reset02 \
SGDC_reset03 \
SGDC_waive23 \
SGDC_waive26 \
SGDC_waive27 \
SGDC_waive29 \
SGDC_libgroup03 \
SGDC_ungroup02 \
_abstractPortSGDC \
SGDC_abstract_port03 \
SGDC_abstract_port04 \
SGDC_abstract_port05 \
SGDC_abstract_port07 \
SGDC_abstract_port08 \
SGDC_abstract_port10 \
SGDC_abstract_port11 \
SGDC_abstract_port12 \
SGDC_abstract_port13 \
SGDC_sdcschema01 \
ReportUngroup \
SGDC_abstract_port21 \
SDC2SGDC_WRN01 \
SDC2SGDC_STX01 \
dftMandatory_Constraint_Check \
dftOptional_Constraint_Check \
dftVSTOPDUSetUp \
dftVSTOPDUExit \
Domain_Conflict01 \
Domain_Matrix01 \
Domain_Missing01 \
SDC_Mapping01 \
SDC2SGDCPARSEW \
SGDC_set_case_analysis_LC \
dftSGDCSTX_059 \
dftSGDCSTX_060 \
dftSGDCSTX_061 \
dftSGDCSTX_069 \
dftFLATDU_RFSetUp \
dftSGDCSTX_057 \
dftUserMacroSanityCheck_01 \
Soc_04 \
dftSGDCSTX_064 \
dftSGDCSTX_070 \
dftSGDCSTX_071 \
Diagnose_ScanChain \
Diagnose_testmode \
Diagnose_testclock \
Info_synthRedundant \
Info_unused \
Info_uncontrollable \
Info_unobservable \
Info_untestable \
Info_coverage \
Info_undetectCause \
Info_testmode \
Info_testmode_conflict_01 \
Info_testclock \
Info_noFault \
Info_noScan \
Info_forcedScan \
Info_inferredNoScan \
Info_scanchain \
Info_scanwrap \
Async_02_capture \
Async_03 \
Async_07 \
Async_08 \
Async_11 \
BIST_01 \
Clock_04 \
Clock_08 \
Clock_09 \
Clock_11 \
Clock_11_capture \
Clock_16 \
Clock_17 \
Clock_21 \
Clock_26 \
Clock_27 \
Clock_28 \
Latch_02 \
Latch_08 \
Latch_10 \
Scan_07 \
Scan_22 \
Scan_24 \
Scan_25 \
Scan_26 \
TA_09 \
Topology_01 \
Topology_02 \
Topology_03 \
Topology_05 \
Topology_10 \
Topology_13 \
Tristate_06 \
Tristate_07_shift \
Info_DftDebugData \
Info_dft_deprecated \
Coverage_audit \
dftFLATDU_RFExit \
AnalyzeBBox \
ReportCheckDataSummary \
}

