# Generated by Django 2.0 on 2017-12-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
