# Generated by Django 2.0.4 on 2018-05-30 09:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_sum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('freq', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('t_slot', models.CharField(max_length=50)),
                ('h_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_host', to='job_sum.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='proj',
            field=models.ManyToManyField(related_name='host_proj', to='job_sum.Proj'),
        ),
        migrations.AddField(
            model_name='host',
            name='queue',
            field=models.ManyToManyField(related_name='host_queue', to='job_sum.Queue'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_host', to='job_sum.Host'),
        ),
    ]
