# Generated by Django 2.0.4 on 2018-06-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_sum', '0004_host_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='host',
            old_name='h_type',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='host',
            name='proj',
        ),
        migrations.RemoveField(
            model_name='host',
            name='queue',
        ),
        migrations.AddField(
            model_name='proj',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='proj_host', to='job_sum.Host'),
        ),
        migrations.AddField(
            model_name='queue',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='queue_host', to='job_sum.Host'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='mem',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem_host', to='job_sum.Host'),
        ),
    ]
