# Generated by Django 2.0.4 on 2018-06-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_sum', '0005_auto_20180605_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mem',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
