# Generated by Django 2.0.4 on 2018-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_sum', '0006_auto_20180606_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mem',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
