# Generated by Django 2.0.4 on 2018-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_sum', '0007_auto_20180606_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
