# Generated by Django 2.0.3 on 2018-03-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('name', 'block', 'owner', 'created_time')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('name', 'flow', 'owner', 'created_time')},
        ),
    ]
