# Generated by Django 2.0.3 on 2018-03-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0002_auto_20180315_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
    ]
