# Generated by Django 2.0.3 on 2018-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0003_auto_20180316_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='flow',
        ),
        migrations.AddField(
            model_name='stage',
            name='flow',
            field=models.ManyToManyField(related_name='stage_flow', to='flow_rpt.Flow'),
        ),
    ]
