# Generated by Django 2.0.3 on 2018-03-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0004_auto_20180316_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('name', 'proj')},
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('name', 'block', 'owner', 'created_time')},
        ),
    ]
