# Generated by Django 2.0.3 on 2018-03-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0006_auto_20180320_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='comment',
        ),
    ]
