# Generated by Django 2.0.4 on 2018-04-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0011_user_proj_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proj_admin',
            field=models.ManyToManyField(blank=True, related_name='user_proj', to='flow_rpt.Proj'),
        ),
    ]
