# Generated by Django 2.0.4 on 2018-07-24 07:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0012_auto_20180418_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_block', to='flow_rpt.Block')),
                ('l_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_l_flow', to='flow_rpt.Flow')),
                ('l_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_l_stage', to='flow_rpt.Stage')),
                ('l_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_l_user', to='flow_rpt.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='signoff',
            unique_together={('name', 'block')},
        ),
    ]
