# Generated by Django 2.1 on 2018-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0013_auto_20180724_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='version',
            field=models.CharField(max_length=200),
        ),
    ]
