# Generated by Django 2.1 on 2018-08-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rpt', '0014_auto_20180802_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='l_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signoff_l_flow', to='flow_rpt.Flow'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='l_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signoff_l_stage', to='flow_rpt.Stage'),
        ),
    ]
