#########################################
set_placement_spacing_label -name Both_0 -side both -lib_cells */AOI32D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_1 -side both -lib_cells */AOI31D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_2 -side both -lib_cells */AOAI211D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_3 -side both -lib_cells */AOI22D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_4 -side both -lib_cells */NR4D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_5 -side both -lib_cells */AOI211D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_6 -side both -lib_cells */ND4D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_7 -side both -lib_cells */AOAI211D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_8 -side both -lib_cells */AOI211D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_9 -side both -lib_cells */AOI31D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_10 -side both -lib_cells */ND4D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_11 -side both -lib_cells */AOI22D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_12 -side both -lib_cells */NR4D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_13 -side both -lib_cells */ND3D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_14 -side both -lib_cells */NR3D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_15 -side both -lib_cells */AOI21D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_16 -side both -lib_cells */ND3D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_17 -side both -lib_cells */NR3D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_18 -side both -lib_cells */AOI21D1BWP240H11P57PDULVT
set_placement_spacing_label -name Both_19 -side both -lib_cells */NR2D1BWP240H8P57PDULVT
set_placement_spacing_label -name Both_20 -side both -lib_cells */NR2D1BWP240H11P57PDULVT
set_placement_spacing_rule -labels {Both_0 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_0 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_1 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_2 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_3 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_4 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_5 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_6 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_7 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_8 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_9 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_10 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_11 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_12 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_13 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_14 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_15 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_16 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_17 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_18 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_19 Both_20} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_0} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_1} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_2} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_3} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_4} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_5} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_6} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_7} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_8} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_9} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_10} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_11} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_12} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_13} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_14} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_15} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_16} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_17} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_18} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_19} {0 0}
set_placement_spacing_rule -labels {Both_20 Both_20} {0 0}
