# Generated by Django 2.0 on 2017-12-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be_rpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_milestone', to='be_rpt.Stage'),
        ),
        migrations.AlterField(
            model_name='block',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_owner', to='be_rpt.User'),
        ),
        migrations.AlterField(
            model_name='block',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_proj', to='be_rpt.Proj'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_owner', to='be_rpt.User'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_version', to='be_rpt.Version'),
        ),
        migrations.AlterField(
            model_name='proj',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_owner', to='be_rpt.User'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_flow', to='be_rpt.Flow'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_owner', to='be_rpt.User'),
        ),
        migrations.AlterField(
            model_name='version',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_block', to='be_rpt.Block'),
        ),
        migrations.AlterField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_owner', to='be_rpt.User'),
        ),
    ]
