# Generated by Django 2.0 on 2017-12-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be_rpt', '0003_auto_20171207_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_proj', to='be_rpt.Proj'),
        ),
    ]
